import {
  NextUIProvider,
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  Link,
  Button,
} from '@nextui-org/react';

import './global.css';
import { default as AppHeader } from '../components/Header/Header';

export const metadata = {
  title: 'Welcome to lunari',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <AppHeader />
          <main className="dark">{children}</main>
          <footer></footer>
        </NextUIProvider>
      </body>
    </html>
  );
}
