'use client';

import {
  NextUIProvider,
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  Link,
  Button,
} from '@nextui-org/react';

import './global.css';
import { default as AppHeader } from '../components/Header/Header';
import { ClerkProvider } from '@clerk/nextjs';
import { usePathname } from 'next/navigation';

// export const metadata = {
//   title: 'Welcome to lunari',
//   description: 'Generated by create-nx-workspace',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const hideHeader = pathname === '/sign-in' || pathname === '/sign-up';
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <NextUIProvider>
            {/* if route is sign-in or sign-up, hide app header */}
            {!hideHeader && <AppHeader />}
            <main className="dark">{children}</main>
            <footer></footer>
          </NextUIProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
